language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - CFLAGS="-O2 -g3 -Wall -Werror"
  matrix:
    - CC=gcc
    - CC=clang

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - phpize && ./configure --silent

script:
  - make
