language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - CFLAGS="-O2 -g3 -Wall -Werror"
  matrix:
    - CC=gcc
    - CC=clang

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

addons:
  apt:
    packages:
      valgrind

before_script:
  - phpize && ./configure --silent && make --silent && make install

script:
  - .travis/run_php_tests.sh

after_failure:
  - .travis/after_failure.sh
